version: '3'
services:
  H:
    image: srinavya123/one:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  HE:
    image: srinavya123/two:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  LI:
    image: srinavya123/three:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  BE:
    image: srinavya123/four:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
