version: '3'
services:
  movies:
    image: srinavya123/lenovo:latest
    ports:
      - "90:80"
    deploy:
      replicas: 3

  train:
    image: srinavya123/hp:latest
    ports:
      - "91:80"
    deploy:
      replicas: 3

  dth:
    image: srinavya123/asus:latest
    ports:
      - "92:80"
    deploy:
      replicas: 3

  recharge:
    image: srinavya123/dell:latest
    ports:
      - "93:80"
    deploy:
      replicas: 3
